[package]
name = "lab_work_sorts"
version = "0.1.0"
authors = ["Dartt0n <antonkudryavtsevdoem@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"